name: CD

on:
  push:
    branches:
      - Development

  pull_request:
    branches:
      - main

jobs:
  entrega:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar bibliotecas
        run: pip install -r bibliotecas.txt

      - name: Preparar aplicacao
        run: |
          mkdir entrega
          cp app.py entrega/
          cp bibliotecas.txt entrega/

      - name: Verificar entrega
        run: ls entrega